### ISSUE TITLE
TODO: update Readme/docs

### ISSUE THREAD

**Issue by pdpino** [hoangnm/react-native-week-view#278]
- [ ] Add png and/or gifs to common-usages.md file
- [ ] "Fixed timetable" description needs an update
- [ ] Add use case demos
  - [ ] Custom EventComponent usage
  - [ ] feature: "allow scrolling one day at the time"
  - [ ] style props usage

More ideas are welcomed (cc @hoangnm @rdewolff), e.g.
- Is it worth creating a dedicated docs webpage? (to avoid overloading github repo with png/gif files)
- I've seen some people forking the project to fully suit their own needs. Hopefully this would not be needed for them, how do we avoid this?
